21:45:37	alter table `tb_turnos_respostas` modify `idtb_entidades` bigint unsigned null	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.208 sec

19:55:57	ALTER TABLE tb_turnos_eventos     DROP FOREIGN KEY tb_turnos_eventos_idtb_turnos_tipos_foreign,     DROP INDEX tb_turnos_eventos_idtb_turnos_tipos_index,     CHANGE COLUMN idtb_turnos_tipos idtb_turnos_eventos_tipos BIGINT UNSIGNED NOT NULL,     ADD INDEX tb_turnos_eventos_idtb_turnos_eventos_tipos_index (idtb_turnos_eventos_tipos),     ADD CONSTRAINT tb_turnos_eventos_idtb_turnos_eventos_tipos_foreign         FOREIGN KEY (idtb_turnos_eventos_tipos)         REFERENCES tb_turnos_eventos_tipos (idtb_turnos_eventos_tipos)         ON DELETE RESTRICT	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.303 sec

19:16:15	CREATE TABLE tb_turnos_respostas (     idtb_turnos_respostas BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,     idtb_entidades BIGINT UNSIGNED NOT NULL,     idtb_formularios_perguntas BIGINT UNSIGNED NOT NULL,     idtb_turnos BIGINT UNSIGNED NOT NULL,     identificador_os VARCHAR(128) NULL,     resposta_txt VARCHAR(256) NULL,     resposta_int INT NULL,     idtb_ativo TINYINT(1) NOT NULL DEFAULT 1,     dt_insert DATETIME NOT NULL,     login_insert VARCHAR(64) NOT NULL,     dt_update DATETIME NULL,     login_update VARCHAR(64) NULL,     PRIMARY KEY (idtb_turnos_respostas),     CONSTRAINT fk_tb_turnos_respostas_entidades FOREIGN KEY (idtb_entidades)         REFERENCES tb_entidades (idtb_entidades)         ON DELETE RESTRICT,     CONSTRAINT fk_tb_turnos_respostas_formularios_perguntas FOREIGN KEY (idtb_formularios_perguntas)         REFERENCES tb_formularios_perguntas (idtb_formularios_perguntas)         ON DELETE RESTRICT,     CONSTRAINT fk_tb_turnos_respostas_turnos FOREIGN KEY (idtb_turnos)         REFERENCES tb_turnos (idtb_turnos)         ON DELETE RESTRICT )	0 row(s) affected, 1 warning(s): 1681 Integer display width is deprecated and will be removed in a future release.	0.294 sec

08:06:02	ALTER TABLE tb_turnos RENAME COLUMN version TO app_version	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.205 sec

21:47:06	CREATE TABLE `tb_turnos_entidades` (     `idtb_turnos_entidades` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,     `idtb_entidades` BIGINT UNSIGNED NOT NULL,     `idtb_turnos` BIGINT UNSIGNED NOT NULL,     `is_motorista` TINYINT(1) NULL,     `idtb_ativo` TINYINT(1) NOT NULL DEFAULT 1,     `dt_insert` DATETIME NOT NULL,     `login_insert` VARCHAR(64) NOT NULL,     `dt_update` DATETIME NULL,     `login_update` VARCHAR(64) NULL,     PRIMARY KEY (`idtb_turnos_entidades`),     INDEX `tb_turnos_entidades_idtb_entidades_index` (`idtb_entidades`),     INDEX `tb_turnos_entidades_idtb_turnos_index` (`idtb_turnos`),     CONSTRAINT `tb_turnos_entidades_idtb_entidades_foreign` FOREIGN KEY (`idtb_entidades`)         REFERENCES `tb_entidades` (`idtb_entidades`)         ON DELETE RESTRICT,     CONSTRAINT `tb_turnos_entidades_idtb_turnos_foreign` FOREIGN KEY (`idtb_turnos`)         REFERENCES `tb_turnos` (`idtb_turnos`)         ON DELETE RESTRICT )  ENGINE=INNODB	0 row(s) affected, 2 warning(s): 1681 Integer display width is deprecated and will be removed in a future release. 1681 Integer display width is deprecated and will be removed in a future release.	0.294 sec

20:25:43	CREATE TABLE `tb_turnos_eventos` (   `idtb_turnos_eventos` bigint unsigned NOT NULL AUTO_INCREMENT,   `id_estrangeiro` bigint unsigned DEFAULT NULL,   `idtb_entidades` bigint unsigned NOT NULL,   `idtb_turnos` bigint unsigned NOT NULL,   `idtb_turnos_tipos` bigint unsigned NOT NULL,   `identificador_os` varchar(128) DEFAULT NULL,   `nome_foto` varchar(128) DEFAULT NULL,   `obs` varchar(256) DEFAULT NULL,   `uniq_evento` varchar(128) NOT NULL,   `latitude` decimal(10,8) NOT NULL,   `longitude` decimal(11,8) NOT NULL,   `quantidade` decimal(10,3) DEFAULT NULL,   `dt_evento` datetime NOT NULL,   `idtb_ativo` tinyint(1) NOT NULL DEFAULT '1',   `dt_insert` datetime NOT NULL,   `login_insert` varchar(64) NOT NULL,   `dt_update` datetime DEFAULT NULL,   `login_update` varchar(64) DEFAULT NULL,   PRIMARY KEY (`idtb_turnos_eventos`),   UNIQUE KEY `tb_turnos_eventos_uniq_evento_unique` (`uniq_evento`),   KEY `tb_turnos_eventos_id_estrangeiro_index` (`id_estrangeiro`),   KEY `tb_turnos_eventos_idtb_entidades_index` (`idtb_entidades`),   KEY `tb_turnos_eventos_idtb_turnos_index` (`idtb_turnos`),   KEY `tb_turnos_eventos_idtb_turnos_tipos_index` (`idtb_turnos_tipos`),   CONSTRAINT `tb_turnos_eventos_idtb_entidades_foreign` FOREIGN KEY (`idtb_entidades`) REFERENCES `tb_entidades` (`idtb_entidades`) ON DELETE RESTRICT,   CONSTRAINT `tb_turnos_eventos_idtb_turnos_foreign` FOREIGN KEY (`idtb_turnos`) REFERENCES `tb_turnos` (`idtb_turnos`) ON DELETE RESTRICT,   CONSTRAINT `tb_turnos_eventos_idtb_turnos_tipos_foreign` FOREIGN KEY (`idtb_turnos_tipos`) REFERENCES `tb_turnos_tipos` (`idtb_turnos_tipos`) ON DELETE RESTRICT ) ENGINE=InnoDB	0 row(s) affected, 1 warning(s): 1681 Integer display width is deprecated and will be removed in a future release.	0.203 sec

20:24:31	CREATE TABLE `tb_turnos_eventos_tipos` (   `idtb_turnos_eventos_tipos` bigint unsigned NOT NULL AUTO_INCREMENT,   `nome` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,   `idtb_ativo` tinyint(1) NOT NULL DEFAULT '1',   `dt_insert` datetime NOT NULL,   `login_insert` varchar(64) NOT NULL,   `dt_update` datetime DEFAULT NULL,   `login_update` varchar(64) DEFAULT NULL,   PRIMARY KEY (`idtb_turnos_eventos_tipos`),   UNIQUE KEY `tb_turnos_eventos_tipos_nome_unique` (`nome`) ) ENGINE=InnoDB	0 row(s) affected, 1 warning(s): 1681 Integer display width is deprecated and will be removed in a future release.	0.196 sec

09:46:01	truncate tb_formularios_perguntas	0 row(s) affected	0.303 sec

09:38:51	UPDATE tb_perguntas  SET      idtb_perguntas_tipos = 4	29 row(s) affected Rows matched: 29  Changed: 29  Warnings: 0	0.176 sec

15:40:54	CREATE TABLE `tb_formularios_perguntas` (   `idtb_formularios_perguntas` bigint unsigned NOT NULL AUTO_INCREMENT,   `idtb_formularios` bigint unsigned NOT NULL,   `idtb_perguntas` bigint unsigned NOT NULL,   `obs` varchar(1024) DEFAULT NULL,   `uniq_formulario_pergunta` varchar(32) GENERATED ALWAYS AS (if((`idtb_ativo` = 1),concat(`idtb_formularios`,_utf8mb4'_',`idtb_perguntas`),NULL)) VIRTUAL,   `ordem` decimal(8,2) DEFAULT NULL,   `peso` int DEFAULT NULL,   `quantidade_minima` int DEFAULT NULL,   `aceita_nao_se_aplica` tinyint(1) DEFAULT NULL,   `resposta_esperada` int DEFAULT NULL,   `idtb_ativo` tinyint(1) NOT NULL DEFAULT '1',   `dt_insert` datetime NOT NULL,   `login_insert` varchar(64) NOT NULL,   `dt_update` datetime DEFAULT NULL,   `login_update` varchar(64) DEFAULT NULL,   PRIMARY KEY (`idtb_formularios_perguntas`),   UNIQUE KEY `tb_formularios_perguntas_uniq_formulario_pergunta_unique` (`uniq_formulario_pergunta`),   KEY `tb_formularios_perguntas_idtb_formularios_foreign` (`idtb_formularios`),   KEY `tb_formularios_perguntas_idtb_perguntas_foreign` (`idtb_perguntas`),   CONSTRAINT `tb_formularios_perguntas_idtb_formularios_foreign` FOREIGN KEY (`idtb_formularios`) REFERENCES `tb_formularios` (`idtb_formularios`) ON DELETE RESTRICT,   CONSTRAINT `tb_formularios_perguntas_idtb_perguntas_foreign` FOREIGN KEY (`idtb_perguntas`) REFERENCES `tb_perguntas` (`idtb_perguntas`) ON DELETE RESTRICT ) ENGINE=InnoDB	0 row(s) affected, 2 warning(s): 1681 Integer display width is deprecated and will be removed in a future release. 1681 Integer display width is deprecated and will be removed in a future release.	0.174 sec

20:49:15	INSERT INTO `tb_perguntas`     (`idtb_perguntas_grupos`, `idtb_perguntas_tipos`, `pergunta`, `idtb_ativo`, `dt_insert`, `login_insert`) VALUES     ('1', '2', 'ÁGUA DE ARREFECIMENTO', '1', NOW(), 'admin'),     ('1', '2', 'ALARME DE RÉ', '1', NOW(), 'admin'),     ('1', '2', 'BUZINA', '1', NOW(), 'admin'),     ('1', '2', 'CATRACA DE AMARRAÇÃO DE ESCADA', '1', NOW(), 'admin'),     ('1', '2', 'CHAVE DE RODA', '1', NOW(), 'admin'),     ('1', '2', 'CINTO DE SEGURANÇA', '1', NOW(), 'admin'),     ('1', '2', 'CONDIÇÕES DA CARROCERIA (ASSOALHO)', '1', NOW(), 'admin'),     ('1', '2', 'ESCADA DE ACESSO À CARROCERIA', '1', NOW(), 'admin'),     ('1', '2', 'ESPELHO RETROVISOR EXTERNO', '1', NOW(), 'admin'),     ('1', '2', 'ESPELHO RETROVISOR INTERNO', '1', NOW(), 'admin'),     ('1', '2', 'EXTINTOR DE INCÊNDIO DA CABINE AUXILIAR', '1', NOW(), 'admin'),     ('1', '2', 'EXTINTOR DE INCÊNDIO DA CABINE PRINCIPAL', '1', NOW(), 'admin'),     ('1', '2', 'FARÓIS', '1', NOW(), 'admin'),     ('1', '2', 'FREIO', '1', NOW(), 'admin'),     ('1', '2', 'FREIO DE MÃO', '1', NOW(), 'admin'),     ('1', '2', 'LANTERNAS', '1', NOW(), 'admin'),     ('1', '2', 'LATARIA E PINTURA', '1', NOW(), 'admin'),     ('1', '2', 'LIMPADOR DE PARA-BRISA', '1', NOW(), 'admin'),     ('1', '2', 'LUZ DE FREIO', '1', NOW(), 'admin'),     ('1', '2', 'LUZ DE RÉ', '1', NOW(), 'admin'),     ('1', '2', 'MACACO', '1', NOW(), 'admin'),     ('1', '2', 'MALLHAU COM BORRACHAS', '1', NOW(), 'admin'),     ('1', '2', 'NÍVEL DE ÓLEO DE FREIO', '1', NOW(), 'admin'),     ('1', '2', 'NÍVEL DE ÓLEO DO MOTOR', '1', NOW(), 'admin'),     ('1', '2', 'PISCA-ALERTA', '1', NOW(), 'admin'),     ('1', '2', 'PNEUS E ESTEPE', '1', NOW(), 'admin'),     ('1', '2', 'PORTA-ESCADA', '1', NOW(), 'admin'),     ('1', '2', 'SETAS', '1', NOW(), 'admin'),     ('1', '2', 'TRIÂNGULO DE SINALIZAÇÃO', '1', NOW(), 'admin')	29 row(s) affected Records: 29  Duplicates: 0  Warnings: 0	0.204 sec

14:04:26	INSERT INTO tb_entidades (     idtb_empresas,     idtb_entidades_tipos,     nome,     idtb_ativo,     dt_insert,     login_insert ) VALUES     (6, 1, '79 || ALEXANDRE BALIEIRO GAMA', 1, NOW(), 'admin'),     (6, 1, '58 || AUGUSTO VENANCIO DA SILVA SANTOS', 1, NOW(), 'admin'),     (6, 1, '68 || ADAUTO LIMA MARINHO', 1, NOW(), 'admin'),     (6, 1, '50 || ARLENE GOMES DA CUNHA', 1, NOW(), 'admin'),     (6, 1, '71 || BRUNO OLIVEIRA', 1, NOW(), 'admin'),     (6, 1, '84 || CARLOS EDUARDO SOARES SILVA', 1, NOW(), 'admin'),     (6, 1, '38 || CLEUVAN CARVALHO DA SILVA', 1, NOW(), 'admin'),     (6, 1, '88 || CLEOMAR DE LIMA RODRIGUES', 1, NOW(), 'admin'),     (6, 1, '16 || CLODOALDO ALVES', 1, NOW(), 'admin'),     (6, 1, '03 || EDGAR RIBEIRO DE SOUZA', 1, NOW(), 'admin'),     (6, 1, '57 || ELIO PEREIRA ALVES', 1, NOW(), 'admin'),     (6, 1, '70 || FEUS BARBOSA DE SOUSA', 1, NOW(), 'admin'),     (6, 1, '75 || GABRYEL ALVES DE OLIVEIRA', 1, NOW(), 'admin'),     (6, 1, '42 || GUIBSON SOUTO DA SILVA', 1, NOW(), 'admin'),     (6, 1, '65 || GUIOMAR PEREIRA DA SILVA', 1, NOW(), 'admin'),     (6, 1, '81 || JANIUSAN CRUZ DA SILVA', 1, NOW(), 'admin'),     (6, 1, '33 || JEFFERSON XAVIER SANTOS', 1, NOW(), 'admin'),     (6, 1, '83 || JOSE PEREIRA ALVES', 1, NOW(), 'admin'),     (6, 1, '27 || JOSE AZEVEDO PEREIRA JUNIOR', 1, NOW(), 'admin'),     (6, 1, '28 || JOSIMAR ARAUJO CABRAL', 1, NOW(), 'admin'),     (6, 1, '40 || JOAO ANTONIO PEREIRA DA SILVA', 1, NOW(), 'admin'),     (6, 1, '59 || LUCAS ALVES LIMA', 1, NOW(), 'admin'),     (6, 1, '82 || LUCIO DOS SANTOS DIAS', 1, NOW(), 'admin'),     (6, 1, '26 || LUCINEY ALMEIDA DE BRITO', 1, NOW(), 'admin'),     (6, 1, '87 || MARCO ANTONIO PEREIRA GUILHERME', 1, NOW(), 'admin'),     (6, 1, '22 || LEANDRO RAMOS DOS SANTOS MATOS', 1, NOW(), 'admin'),     (6, 1, '63 || NAIRTON VITORINO FERREIRA', 1, NOW(), 'admin'),     (6, 1, '54 || PEDRO LUCAS RODRIGUES AMORIM', 1, NOW(), 'admin'),     (6, 1, '34 || PEDRO FERREIRA CAMPOS', 1, NOW(), 'admin'),     (6, 1, '46 || RICARDO MOREIRA BARROS', 1, NOW(), 'admin'),     (6, 1, '77 || RODRIGO CARVALHO DA COSTA', 1, NOW(), 'admin'),     (6, 1, '39 || RENATO DA COSTA LEITE', 1, NOW(), 'admin'),     (6, 1, '35 || SAMOEL PINTO DE MELO', 1, NOW(), 'admin'),     (6, 1, '36 || VICTOR HUGO PEREIRA AIRES', 1, NOW(), 'admin'),     (6, 1, '72 || WANDERSON FERREIRA CARDEAL', 1, NOW(), 'admin'),     (6, 1, '86 || WASHINGTON LUIZ DE SOUZA OLIVEIRA', 1, NOW(), 'admin'),     (6, 1, '74 || ZERONILDE FRANCISCO BISPO', 1, NOW(), 'admin'),     (6, 1, '85 || ISABELLA WARDA ASSENCIO REIS', 1, NOW(), 'admin'),     (6, 1, '49 || DJUNIOR LUCIO RAMALHO', 1, NOW(), 'admin')	39 row(s) affected Records: 39  Duplicates: 0  Warnings: 0	0.231 sec

11:12:37	ALTER TABLE flutter_log   ADD COLUMN status_code INT NULL AFTER api_version,   ADD INDEX flutter_log_status_code_dt_evento_index (status_code, dt_evento)	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.298 sec

14:43:53	ALTER TABLE flutter_log  DROP FOREIGN KEY flutter_log_idflutter_log_token_foreign	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.285 sec

22:09:50	ALTER TABLE `flutter_log`  ADD CONSTRAINT `flutter_log_idflutter_log_token_foreign`  FOREIGN KEY (`idflutter_log_token`) REFERENCES `flutter_log` (`idflutter_log`)  ON DELETE RESTRICT	361 row(s) affected Records: 361  Duplicates: 0  Warnings: 0	0.272 sec

22:09:50	ALTER TABLE `flutter_log`  ADD KEY `flutter_log_idflutter_log_token_index` (`idflutter_log_token`)	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.182 sec

22:09:50	ALTER TABLE `flutter_log`  ADD COLUMN `idflutter_log_token` BIGINT UNSIGNED DEFAULT NULL AFTER `idflutter_log`	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.189 sec

10:03:01	CREATE TABLE `tb_turnos` (   `idtb_turnos` bigint unsigned NOT NULL AUTO_INCREMENT,   `idflutter_log` bigint unsigned DEFAULT NULL,   `idtb_empresas` bigint unsigned NOT NULL,   `idtb_entidades` bigint unsigned NOT NULL,   `idtb_equipes` bigint unsigned NOT NULL,   `idtb_turnos_tipos` bigint unsigned NOT NULL,   `km_inicial` int DEFAULT NULL,   `km_final` int DEFAULT NULL,   `version` int NOT NULL,   `dt_inicio` datetime NOT NULL,   `dt_fim` datetime DEFAULT NULL,   `idtb_ativo` tinyint(1) NOT NULL DEFAULT '1',   `dt_insert` datetime NOT NULL,   `login_insert` varchar(64) NOT NULL,   `dt_update` datetime DEFAULT NULL,   `login_update` varchar(64) DEFAULT NULL,   PRIMARY KEY (`idtb_turnos`),   KEY `tb_turnos_idflutter_log_index` (`idflutter_log`),   CONSTRAINT `tb_turnos_idflutter_log_foreign` FOREIGN KEY (`idflutter_log`) REFERENCES `flutter_log` (`idflutter_log`) ON DELETE RESTRICT ) ENGINE=InnoDB	0 row(s) affected, 1 warning(s): 1681 Integer display width is deprecated and will be removed in a future release.	0.309 sec

10:03:00	CREATE TABLE `tb_equipes` (   `idtb_equipes` bigint unsigned NOT NULL AUTO_INCREMENT,   `idtb_empresas` bigint unsigned NOT NULL,   `idtb_equipes_tipos` bigint unsigned NOT NULL,   `nome` varchar(64) NOT NULL,   `idtb_ativo` tinyint(1) NOT NULL DEFAULT '1',   `dt_insert` datetime NOT NULL,   `login_insert` varchar(64) NOT NULL,   `dt_update` datetime DEFAULT NULL,   `login_update` varchar(64) DEFAULT NULL,   PRIMARY KEY (`idtb_equipes`),   UNIQUE KEY `uq_idtb_empresas_plus_nome` (`idtb_empresas`,`nome`),   KEY `tb_equipes_idtb_empresas_index` (`idtb_empresas`),   KEY `tb_equipes_idtb_equipes_tipos_index` (`idtb_equipes_tipos`),   CONSTRAINT `tb_equipes_idtb_empresas_foreign` FOREIGN KEY (`idtb_empresas`) REFERENCES `tb_empresas` (`idtb_empresas`) ON DELETE RESTRICT,   CONSTRAINT `tb_equipes_idtb_equipes_tipos_foreign` FOREIGN KEY (`idtb_equipes_tipos`) REFERENCES `tb_equipes_tipos` (`idtb_equipes_tipos`) ON DELETE RESTRICT ) ENGINE=InnoDB	0 row(s) affected, 1 warning(s): 1681 Integer display width is deprecated and will be removed in a future release.	0.306 sec

10:03:00	CREATE TABLE `tb_equipes_tipos` (   `idtb_equipes_tipos` bigint unsigned NOT NULL AUTO_INCREMENT,   `nome` varchar(64) NOT NULL,   `idtb_ativo` int NOT NULL DEFAULT '1',   `dt_insert` datetime NOT NULL,   `login_insert` varchar(64) NOT NULL,   `dt_update` datetime DEFAULT NULL,   `login_update` varchar(64) DEFAULT NULL,   PRIMARY KEY (`idtb_equipes_tipos`),   UNIQUE KEY `tb_equipes_tipos_nome_unique` (`nome`) ) ENGINE=InnoDB	0 row(s) affected	0.205 sec

10:02:59	CREATE TABLE `tb_entidades` (   `idtb_entidades` bigint unsigned NOT NULL AUTO_INCREMENT,   `idtb_empresas` bigint unsigned NOT NULL,   `idtb_entidades_tipos` bigint unsigned NOT NULL,   `nome` varchar(256) NOT NULL,   `idtb_ativo` tinyint(1) NOT NULL DEFAULT '1',   `dt_insert` datetime NOT NULL,   `login_insert` varchar(64) NOT NULL,   `dt_update` datetime DEFAULT NULL,   `login_update` varchar(64) DEFAULT NULL,   PRIMARY KEY (`idtb_entidades`),   KEY `tb_entidades_idtb_empresas_index` (`idtb_empresas`),   KEY `tb_entidades_idtb_entidades_tipos_index` (`idtb_entidades_tipos`),   CONSTRAINT `tb_entidades_idtb_empresas_foreign` FOREIGN KEY (`idtb_empresas`) REFERENCES `tb_empresas` (`idtb_empresas`) ON DELETE RESTRICT,   CONSTRAINT `tb_entidades_idtb_entidades_tipos_foreign` FOREIGN KEY (`idtb_entidades_tipos`) REFERENCES `tb_entidades_tipos` (`idtb_entidades_tipos`) ON DELETE RESTRICT ) ENGINE=InnoDB	0 row(s) affected, 1 warning(s): 1681 Integer display width is deprecated and will be removed in a future release.	0.215 sec

10:02:59	CREATE TABLE `tb_entidades_tipos` (   `idtb_entidades_tipos` bigint unsigned NOT NULL AUTO_INCREMENT,   `nome` varchar(64) NOT NULL,   `idtb_ativo` tinyint(1) NOT NULL DEFAULT '1',   `dt_insert` datetime NOT NULL,   `login_insert` varchar(64) NOT NULL,   `dt_update` datetime DEFAULT NULL,   `login_update` varchar(64) DEFAULT NULL,   PRIMARY KEY (`idtb_entidades_tipos`),   UNIQUE KEY `tb_entidades_tipos_nome_unique` (`nome`) ) ENGINE=InnoDB	0 row(s) affected, 1 warning(s): 1681 Integer display width is deprecated and will be removed in a future release.	0.204 sec

10:02:59	CREATE TABLE `tb_turnos_tipos` (     `idtb_turnos_tipos` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,     `nome` VARCHAR(64) NOT NULL,     `idtb_ativo` TINYINT(1) NOT NULL DEFAULT '1',     `dt_insert` DATETIME NOT NULL,     `login_insert` VARCHAR(64) NOT NULL,     `dt_update` DATETIME DEFAULT NULL,     `login_update` VARCHAR(64) DEFAULT NULL,     PRIMARY KEY (`idtb_turnos_tipos`),     UNIQUE KEY `tb_turnos_tipos_nome_unique` (`nome`) )  ENGINE=INNODB	0 row(s) affected, 1 warning(s): 1681 Integer display width is deprecated and will be removed in a future release.	0.296 sec

23:23:14	ALTER TABLE tb_animais ADD CONSTRAINT tb_animais_tbfk_3 FOREIGN KEY (idtb_empresas) REFERENCES tb_empresas(idtb_empresas)	37 row(s) affected Records: 37  Duplicates: 0  Warnings: 0	0.251 sec

23:23:05	ALTER TABLE tb_empresas     ADD CONSTRAINT tb_empresas_cnpj_unique     UNIQUE (cnpj)	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.204 sec

23:23:00	ALTER TABLE tb_empresas     DROP INDEX cnpj_UNIQUE	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.221 sec

23:22:54	ALTER TABLE tb_empresas     MODIFY COLUMN login_update VARCHAR(64) DEFAULT NULL	3 row(s) affected Records: 3  Duplicates: 0  Warnings: 0	0.308 sec

23:22:46	ALTER TABLE tb_empresas     MODIFY COLUMN login_insert VARCHAR(64) DEFAULT NULL	3 row(s) affected Records: 3  Duplicates: 0  Warnings: 0	0.307 sec

23:22:41	ALTER TABLE tb_empresas     MODIFY COLUMN idtb_ativo TINYINT(1) NOT NULL DEFAULT 1	3 row(s) affected, 1 warning(s): 1681 Integer display width is deprecated and will be removed in a future release. Records: 3  Duplicates: 0  Warnings: 1	0.309 sec

23:22:36	ALTER TABLE tb_empresas     MODIFY COLUMN idtb_empresas BIGINT UNSIGNED NOT NULL AUTO_INCREMENT	3 row(s) affected Records: 3  Duplicates: 0  Warnings: 0	0.308 sec

23:22:31	ALTER TABLE tb_animais MODIFY idtb_empresas BIGINT UNSIGNED NOT NULL	37 row(s) affected Records: 37  Duplicates: 0  Warnings: 0	0.306 sec

23:22:26	ALTER TABLE tb_animais DROP FOREIGN KEY tb_animais_tbfk_3	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	0.204 sec

--

ALTER TABLE tb_animais
DROP FOREIGN KEY tb_animais_tbfk_3;

ALTER TABLE tb_animais
MODIFY idtb_empresas BIGINT UNSIGNED NOT NULL;

ALTER TABLE tb_empresas
    MODIFY COLUMN idtb_empresas BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE tb_empresas
    MODIFY COLUMN idtb_ativo TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE tb_empresas
    MODIFY COLUMN login_insert VARCHAR(64) DEFAULT NULL;

ALTER TABLE tb_empresas
    MODIFY COLUMN login_update VARCHAR(64) DEFAULT NULL;

ALTER TABLE tb_empresas
    DROP INDEX cnpj_UNIQUE;

ALTER TABLE tb_empresas
    ADD CONSTRAINT tb_empresas_cnpj_unique
    UNIQUE (cnpj);

ALTER TABLE tb_animais
ADD CONSTRAINT tb_animais_tbfk_3
FOREIGN KEY (idtb_empresas)
REFERENCES tb_empresas(idtb_empresas);

-- 20260726;
